# Generated by Django 5.0.3 on 2024-03-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=255)),
                ('cnn', models.IntegerField()),
                ('location_description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('block_lot', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('lot', models.CharField(max_length=255)),
                ('permit', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('food_items', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('schedule', models.CharField(max_length=255)),
                ('days_hours', models.CharField(max_length=255)),
                ('approved', models.DateTimeField(blank=True, null=True)),
                ('received', models.DateTimeField(blank=True, null=True)),
                ('prior_permit', models.IntegerField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('fire_prevention_districts', models.IntegerField()),
                ('police_districts', models.IntegerField()),
                ('supervisor_districts', models.IntegerField()),
                ('zip_codes', models.IntegerField()),
                ('neighborhoods', models.CharField(max_length=255)),
            ],
        ),
    ]
